### ISSUE TITLE
Caching Responces

### ISSUE THREAD

**Issue by aRealCatTBH** [chocololat/discord-lookup-api#2]
If someone really wanted to, it seems you don't have any cache and/or rate limiting on the api, anyone could get your bot deleted, discord may also give consequences to the users account not so sure about that last bit though.

**Comment by chocololat** [comment]
yup, this is a major issue that I didn't think about when I first made the API, i need to do it

**Comment by chocololat** [comment]
the commit I pushed should address it 👍 thanks for the issue !
